import Head from "next/head";
import { AiFillLinkedin, AiFillGithub, AiOutlineMail } from "react-icons/ai";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Raleway:wght@500&display=swap');
        </style>
      </Head>

      <main>
        <div className="bg-gradient-to-b from-emerald to-skyBlue">
          <div>
            <h2 className="text-3xl text-center">Micah Bottoms</h2>
          </div>
          <nav className="py-4 mb-6 flex justify-between">
            <ul className="flex items-center">
              <li>
                <a href="">About Me</a>
              </li>
              <li>
                <a href="#projects">Projects</a>
              </li>
              <li>
                <a href="">Find Me</a>
              </li>
            </ul>
          </nav>
        </div>

        <div>
          <div></div>
          <div>
            <div id="projects" className="flex flex-col">
              <h3>Projects</h3>
              <div className="basis-1/3 flex-1 bg-yellow-400">hello</div>
              <div className="basis-1/3 flex-1 bg-yellow-400">hello</div>
              <div className="basis-1/3 flex-1 bg-yellow-400">hello</div>
              <div className="box-content bg-yellow-400">hello</div>
            </div>
          </div>
        </div>

        <div className=" text-4xl flex justify-center gap-12 m-2">
          <a
            href="https://www.linkedin.com/in/micah-bottoms-09a096246/"
            target="_blank"
          >
            <AiFillLinkedin />
          </a>

          <a href="https://github.com/mbottoms3" target="_blank">
            <AiFillGithub />
          </a>

          <a href="mailto: bottoms.micah.3@gmail.com">
            <AiOutlineMail />
          </a>
        </div>
      </main>
    </div>
  );
}
